### ISSUE TITLE
Setup the Lighthouse Lambda

### ISSUE THREAD

**Issue by DuncanLewis** [DuncanLewis/lighthouse-auditor#1]
# Tasks

- [x] Setup the serverless framework
- [ ] Create the auditor Lambda function to invoke a Lighthouse test

# AC 

- [ ] Serverless infrastructure can be deploy to AWS
- [ ] When passed a URL the auditor function should run a Lighthouse test on given URL - nothing is expected to happen with results
