### ISSUE TITLE
Save Lighthouse results to DynamoDB

### ISSUE THREAD

**Issue by DuncanLewis** [DuncanLewis/lighthouse-auditor#2]
# Tasks

- [ ] Add DynamoDB resource to Serverless
- [ ] Create new Lambda function to save Lighthouse data when passed the output
- [ ] Decide on approach to getting data between Auditor and Save functions

# AC 

- [ ] When passed an output from Lighthouse save data into DynamoDB table
- [ ] Decide on method to transport data between Auditor function and save function - this will either be by invoking the save function directly from the Auditor function or using AWS Step Functions.
